/**
 * The ROLePlay block: everything the template writes after the "ROLePlay Data
 * ->" divider, and everything neither capture can speak for.
 *
 * These columns hold modelling output -- expected loss, PMLs, ROLs, portfolio
 * names, reinsurer lists. The download request does not carry them and the
 * table on screen does not show them; the server joins them in when it builds
 * the workbook. Of the 144, 68 hold a value that appears in neither
 * payload_data.json nor table_data.json, so no amount of mapping would reach
 * them. Verifying these needs the download RESPONSE captured, which nothing
 * does yet.
 *
 * Listed by name rather than as "everything after the divider" on purpose. A
 * rule would quietly excuse a column added in a future release; a list does
 * not, so a new one is reported as unchecked the first time it appears and
 * somebody decides where it belongs.
 *
 * The block is absent entirely from templates downloaded without ROLePlay data,
 * which is why the divider's fill is declared optional and these names simply
 * do not come up.
 */
export const ROLEPLAY_BLOCK = [
  "Edison Program ID",
  "Edison Program Name",
  "Edison Program Type",
  "Edison View of Risk",
  "Company",
  "GCMP Company ID",
  "GCMP Placement Name",
  "GCMP Placement ID",
  "GC Ref No. / ReVision Program No.",
  "Last Modified Date",
  "Inception Date",
  "Expiration Date",
  "GCMP Placement Types",
  "Inception Year",
  "Sub Class",
  "Estimated Subject Premium",
  "Policy Surplus",
  "Geo Scope",
  "Office Id",
  "GCMP Tier 2 Region",
  "GCMP Tier 3 Region",
  "GCMP Tier 4 Region",
  "GCMP Tier 5 Region",
  "GCMP Layer ID",
  "Edison Treaty ID",
  "Layer Number",
  "Layer Currency",
  "FX Date",
  "GCMP USD Rate",
  "Property COE Geo Scope",
  "Property COE Segment",
  "Layer Geo Scope",
  "Loss Impacted",
  "Risk-Adj Rate ∆ (%)",
  "Risk-Adj Method",
  "Any Non-Concurrent",
  "Total Placement %",
  "Edison Placement %",
  "Non-Concurrent Placement %",
  "MR Placement %",
  "# Of Reinsurers",
  "List Of Reinsurers",
  "Limit",
  "Attachment",
  "Layer Comments",
  "GCMP Contract Types",
  "GCMP Layer Specific Coverage",
  "GCMP Deposit Premium @ 100% Placed",
  "Modeled Deposit Premium @ 100% Placed",
  "Modeled Expected Premium @ 100% Placed",
  "Modeled Reinstatement Premium @ 100% Placed",
  "GCMP Reinstatements",
  "Number Of MR Reinstatements",
  "GCMP ROL",
  "Modeled ROL",
  "Portfolio Name",
  "Expected Loss @ 100% Placed",
  "Standard Deviation @ 100% Placed",
  "CV",
  "LOL",
  "Loss Ratio",
  "Risk Load",
  "RP Attach",
  "RP Exhaust Limit 1",
  "RP Exhaust Limit 2",
  "RP Exhaust Limit 3",
  "RP Exhaust Limit 4",
  "RP Exhaust Limit 5",
  "RP Exhaust Limit 10",
  "RP Exhaust Limit 15",
  "RP Exhaust Limit 20",
  "RP Exhaust Limit 25",
  "RP Exhaust Limit Max",
  "Expected Loss EQ",
  "Demand Surge EQ",
  "Expected Loss SCS",
  "Demand Surge SCS",
  "Expected Loss WT",
  "Demand Surge WT",
  "Expected Loss WF",
  "Demand Surge WF",
  "NetPreCat AAL",
  "NetPreCat OEP 2 Yr PML",
  "NetPreCat OEP 5 Yr PML",
  "NetPreCat OEP 6 Yr PML",
  "NetPreCat OEP 10 Yr PML",
  "NetPreCat OEP 20 Yr PML",
  "NetPreCat OEP 25 Yr PML",
  "NetPreCat OEP 50 Yr PML",
  "NetPreCat OEP 100 Yr PML",
  "NetPreCat OEP 200 Yr PML",
  "NetPreCat OEP 250 Yr PML",
  "NetPreCat OEP 500 Yr PML",
  "NetPreCat OEP 1000 Yr PML",
  "NetPreCat OEP 2500 Yr PML",
  "NetPreCat OEP 5000 Yr PML",
  "NetPreCat AEP 2 Yr PML",
  "NetPreCat AEP 5 Yr PML",
  "NetPreCat AEP 6 Yr PML",
  "NetPreCat AEP 10 Yr PML",
  "NetPreCat AEP 20 Yr PML",
  "NetPreCat AEP 25 Yr PML",
  "NetPreCat AEP 50 Yr PML",
  "NetPreCat AEP 100 Yr PML",
  "NetPreCat AEP 200 Yr PML",
  "NetPreCat AEP 250 Yr PML",
  "NetPreCat AEP 500 Yr PML",
  "NetPreCat AEP 1000 Yr PML",
  "NetPreCat AEP 2500 Yr PML",
  "NetPreCat AEP 5000 Yr PML",
  "Edison Source",
  "GC Modeled",
  "Event ID Match",
  "Currency Conversion",
  "MetaRisk Base Currency",
  "GCMP USD Rate for MetaRisk Base Currency",
  "Personal/Private Lines Mix (%)",
  "Commercial/Industrial Lines Mix (%)",
  "Direct Insurance Mix (%)",
  "Assumed Reinsurance Mix (%)",
  "Expected TIV Change (%)",
  "Expected TIV Change Reason",
  "TIV % Change included in Modeling",
  "Occurrence XOL treaties not included in the Edison program?",
  "Occurrence XOL Attachment",
  "Occurrence XOL Attachment Currency",
  "Occurrence XOL Exhaust",
  "Occurrence XOL Exhaust Currency",
  "Aggregate XOL treaties not included in the Edison program?",
  "Aggregate XOL Attachment",
  "Aggregate XOL Attachment Currency",
  "Aggregate XOL Exhaust",
  "Aggregate XOL Exhaust Currency",
  "Quota Share",
  "Amount Ceded (%)",
  "Expiring Program Retention",
  "Expiring Program Retention Currency",
  "Renewal Program Retention",
  "Renewal Program Retention Currency",
  "Expiring Program Attachment (Return Period)",
  "Renewal Program Attachment (Return Period)",
  "Does RA flat calculation include inflation?",
  "Is grossing up to 100% placement applicable?",
  "Grossing up to 100% placement inapplicability explanation",
];
